### ISSUE TITLE
eureka同步到nacos报空指针

### ISSUE THREAD

**Issue by jeremy7xu** [nacos-group/nacos-sync#149]
![image](https://user-images.githubusercontent.com/31699314/82273598-738aee00-99b0-11ea-9f6c-ad7c9e4c0ed0.png)

**Comment by jeremy7xu** [comment]
java.lang.NullPointerException: null
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:90)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:55)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)

**Comment by paderlol** [comment]
你eureka集群配置不对

**Comment by paderlol** [comment]
http://IP:port/eureka

**Comment by jeremy7xu** [comment]
> http://IP:port/eureka
多谢纠正，但是我修改后又出现了这个报错
Caused by: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Root name 'timestamp' does not match expected ('application') for type [simple type, class com.netflix.discovery.shared.Application]; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'timestamp' does not match expected ('application') for type [simple type, class com.netflix.discovery.shared.Application]
 at [Source: (PushbackInputStream); line: 1, column: 2]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:243)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:225)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:100)
	... 29 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Root name 'timestamp' does not match expected ('application') for type [simple type, class com.netflix.discovery.shared.Application]
 at [Source: (PushbackInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1355)
	at com.fasterxml.jackson.databind.ObjectMapper._unwrapAndDeserialize(ObjectMapper.java:4087)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4011)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:237)

**Comment by paderlol** [comment]
没获取到对应application，我推测可能是eureka版本不兼容导致的

**Comment by jeremy7xu** [comment]
我们的cloud版本是Dalston.SR3，这样的话我降一下nacosSync的版本试试

**Comment by paderlol** [comment]
Finchley.SR2/Greenwich.SR1这两个版本我刚试了都没问题的

**Comment by jeremy7xu** [comment]
好的，感谢！
