### ISSUE TITLE
 从Eureka同步到nacos，不能同步么？

### ISSUE THREAD

**Issue by cncentoscn** [nacos-group/nacos-sync#171]
020-09-23 16:36:05.143 ERROR com.alibaba.nacossync.extension.holder.AbstractServerHolderImpl Line:48  - clusterId=1fdc0f56ea8b9572bf033124a2cefc8a, start server failed
java.lang.IllegalArgumentException: Malformed serviceUrl: 10.1.1.2:8001/eureka/
	at com.netflix.discovery.shared.resolver.DefaultEndpoint.<init>(DefaultEndpoint.java:45)
	at com.alibaba.nacossync.extension.holder.EurekaServerHolder.createServer(EurekaServerHolder.java:37)
	at com.alibaba.nacossync.extension.holder.EurekaServerHolder.createServer(EurekaServerHolder.java:30)
	at com.alibaba.nacossync.extension.holder.AbstractServerHolderImpl.lambda$get$1(AbstractServerHolderImpl.java:45)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.alibaba.nacossync.extension.holder.AbstractServerHolderImpl.get(AbstractServerHolderImpl.java:42)
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:88)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:57)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-23 16:36:05.143 INFO  com.alibaba.nacossync.extension.holder.AbstractServerHolderImpl Line:44  - Starting create cluster server, clusterId=4efc44bd5286e4dfb2649b7f66865c6e
2020-09-23 16:36:05.294 ERROR com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl Line:105 - sync task from eureka to nacos was failed, taskId:251d5bd32751e0dbbff53f24b27d28ef
java.lang.NullPointerException: null
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:90)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:57)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-23 16:36:05.299 INFO  com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:86  - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=2, taskId=251d5bd32751e0dbbff53f24b27d28ef, sourceClusterId=1fdc0f56ea8b9572bf033124a2cefc8a, destClusterId=4efc44bd5286e4dfb2649b7f66865c6e, serviceName=Sync, version=, groupName=Sync, nameSpace=null, taskStatus=SYNC, workerIp=10.1.1.95, operationId=ae887f72-d127-4198-a2d2-2882ecee0965)
2020-09-23 16:37:34.469 INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:180 - Initializing Spring FrameworkServlet 'dispatcherServlet'
2020-09-23 16:37:34.469 INFO  org.springframework.web.servlet.DispatcherServlet Line:494 - FrameworkServlet 'dispatcherServlet': initialization started
2020-09-23 16:37:34.486 INFO  org.springframework.web.servlet.DispatcherServlet Line:509 - FrameworkServlet 'dispatcherServlet': initialization completed in 17 ms

**Comment by cncentoscn** [comment]
2020-09-23 16:52:40.780 ERROR com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl Line:105 - sync task from eureka to nacos was failed, taskId:251d5bd32751e0dbbff53f24b27d28ef
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://10.0.0.106:8001/eureka/apps/Sync": Connection timed out (Connection timed out); nested exception is java.net.ConnectException: Connection timed out (Connection timed out)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:696)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:564)
	at org.springframework.cloud.netflix.eureka.http.RestTemplateEurekaHttpClient.getApplication(RestTemplateEurekaHttpClient.java:181)
	at com.alibaba.nacossync.extension.eureka.EurekaNamingService.getApplications(EurekaNamingService.java:54)
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:90)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:57)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:687)
	... 26 common frames omitted
2020-09-23 16:52:40.785 INFO  com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:86  - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=3, taskId=251d5bd32751e0dbbff53f24b27d28ef, sourceClusterId=1fdc0f56ea8b9572bf033124a2cefc8a, destClusterId=4efc44bd5286e4dfb2649b7f66865c6e, serviceName=Sync, version=, groupName=Sync, nameSpace=null, taskStatus=SYNC, workerIp=10.1.1.95, operationId=3186ec5b-e281-43d3-bf6b-9b711e72ab11)
