### ISSUE TITLE
从EUREKA同步到nacos，没反应呢。

### ISSUE THREAD

**Issue by cncentoscn** [nacos-group/nacos-sync#172]
2020-09-23 16:58:13.363 INFO  springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator Line:40  - Generating unique operation named: handleUsingGET_19
2020-09-23 16:58:13.384 INFO  springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator Line:40  - Generating unique operation named: deleteTaskUsingDELETE_1
2020-09-23 16:58:13.392 INFO  springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator Line:40  - Generating unique operation named: getByTaskIdUsingGET_1
2020-09-23 16:58:13.395 INFO  springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator Line:40  - Generating unique operation named: taskAddUsingPOST_1
2020-09-23 16:58:13.415 INFO  springfox.documentation.spring.web.readers.operation.CachingOperationNameGenerator Line:40  - Generating unique operation named: tasksUsingGET_1
2020-09-23 16:58:13.465 INFO  org.apache.coyote.http11.Http11NioProtocol Line:180 - Starting ProtocolHandler ["http-nio-8081"]
2020-09-23 16:58:13.471 INFO  org.apache.tomcat.util.net.NioSelectorPool Line:180 - Using a shared selector for servlet write/read
2020-09-23 16:58:13.485 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer Line:206 - Tomcat started on port(s): 8081 (http) with context path ''
2020-09-23 16:58:13.488 INFO  com.alibaba.nacossync.NacosSyncMain Line:59  - Started NacosSyncMain in 8.863 seconds (JVM running for 9.324)
2020-09-23 16:58:13.551 INFO  org.hibernate.hql.internal.QueryTranslatorFactoryInitiator Line:47  - HHH000397: Using ASTQueryTranslatorFactory
2020-09-23 16:58:13.749 INFO  com.alibaba.nacossync.extension.holder.AbstractServerHolderImpl Line:44  - Starting create cluster server, clusterId=1fdc0f56ea8b9572bf033124a2cefc8a
2020-09-23 16:58:13.855 INFO  com.alibaba.nacossync.extension.holder.AbstractServerHolderImpl Line:44  - Starting create cluster server, clusterId=4efc44bd5286e4dfb2649b7f66865c6e
2020-09-23 16:58:14.247 INFO  com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:86  - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=4, taskId=251d5bd32751e0dbbff53f24b27d28ef, sourceClusterId=1fdc0f56ea8b9572bf033124a2cefc8a, destClusterId=4efc44bd5286e4dfb2649b7f66865c6e, serviceName=Sync, version=, groupName=Sync, nameSpace=null, taskStatus=SYNC, workerIp=10.1.1.95, operationId=feabad09-94c4-4604-acbb-e99f75efe130)

2020-09-23 17:00:51.844 INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:180 - Initializing Spring FrameworkServlet 'dispatcherServlet'
2020-09-23 17:00:51.845 INFO  org.springframework.web.servlet.DispatcherServlet Line:494 - FrameworkServlet 'dispatcherServlet': initialization started
2020-09-23 17:00:51.870 INFO  org.springframework.web.servlet.DispatcherServlet Line:509 - FrameworkServlet 'dispatcherServlet': initialization completed in 25 ms

**Comment by xiarixigua** [comment]
我也遇到一样的问题，把同步服务的服务名改成Eureka的Application名就好了

**Comment by cncentoscn** [comment]
> 我也遇到一样的问题，把同步服务的服务名改成Eureka的Application名就好了

2020-09-23 19:08:25.888 INFO  com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl Line:116 - Add service instance from Eureka, serviceName=ADMIN-API, Ip=10.1.1.4, port=8130
2020-09-23 19:08:25.891 ERROR com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl Line:105 - sync task from eureka to nacos was failed, taskId:5f55de56f1240a1c7d9c7f0aed71e3de
com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([10.1.1.95:8848 ]) tried: java.net.URISyntaxException: Illegal character in authority at index 7: http://10.1.1.95:8848 /nacos/v1/ns/instance?app=unknown&groupName=DEFAULT_GROUP&metadata=%7B%22management.port%22%3A%228130%22%2C%22destClusterId%22%3A%22f25df9683702cbc8fb629eb4eb74860a%22%2C%22syncSource%22%3A%22EUREKA%22%2C%22sourceClusterId%22%3A%221fdc0f56ea8b9572bf033124a2cefc8a%22%7D&namespaceId=public&port=8130&enable=true&healthy=true&ip=10.1.1.4&weight=1.0&ephemeral=true&serviceName=DEFAULT_GROUP%40%40ADMIN-API
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:190)
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.addValidInstance(EurekaSyncToNacosServiceImpl.java:118)
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:101)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:57)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-09-23 19:08:25.892 INFO  com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:86  - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=9, taskId=5f55de56f1240a1c7d9c7f0aed71e3de, sourceClusterId=1fdc0f56ea8b9572bf033124a2cefc8a, destClusterId=f25df9683702cbc8fb629eb4eb74860a, serviceName=ADMIN-API, version=, groupName=, nameSpace=null, taskStatus=SYNC, workerIp=10.1.1.95, operationId=3dd07909-c1cb-4ca3-9097-1ac1b8391945)

试了下不行哦

**Comment by paderlol** [comment]
这是说你的配置的地址似乎格式有问题，好像有空格
