### ISSUE TITLE
更新0.4.6之后，0.4.5的相同配置无法运行同步

### ISSUE THREAD

**Issue by Jadaiah** [nacos-group/nacos-sync#232]
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:172)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:146)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:223)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:212)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:200)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:179)
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:93)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:57)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:628)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:608)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:203)
	... 31 common frames omitted

**Comment by paderlol** [comment]
如果没有使用Nacos2.0，就不要使用这个版本

**Comment by mushroom11s** [comment]
> 如果没有使用Nacos2.0，就不要使用这个版本

我使用了Nacos2.0 具体版本 docker hub 上  2.0.0-bugfix ，出现了同样的问题
没有找到nacos-sync得使用文档呀，还要看源码😐

**Comment by paderlol** [comment]
同样的什么问题?麻烦说清楚 是从哪里同步到Nacos 或者是Nacos同步到哪里,并且把错误贴出来 谢谢

**Comment by paderlol** [comment]
例子工程 在我自己github下面, 我等下把地址贴到README里面

**Comment by mushroom11s** [comment]
> 同样的什么问题?麻烦说清楚 是从哪里同步到Nacos 或者是Nacos同步到哪里,并且把错误贴出来 谢谢

eureka->nacos 同样的错误日志，刚刚拉了一个2.0.1的nacos就成功了。会不会是 2.0.0-bugfix 和这个版本之间的问题？
