### ISSUE TITLE
java.lang.NullPointerException: task from zk--> nacos

### ISSUE THREAD

**Issue by xingtaoshi** [nacos-group/nacos-sync#59]
2019-01-24 17:51:34.649 ERROR com.alibaba.nacossync.extension.impl.ZookeeperSyncToNacosServiceImpl Line:149 - sync task from zookeeper to nacos was failed, taskId:3475b1b5c930dfe1f4f19001155c7e87
java.lang.NullPointerException: null
        at com.alibaba.nacossync.extension.impl.ZookeeperSyncToNacosServiceImpl.sync(ZookeeperSyncToNacosServiceImpl.java:93)
        at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:55)
        at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:80)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:71)

**Comment by paderlol** [comment]
看一下是不是zk配置没有配对，或者nacos


| |
浮夸
|
|
邮箱：huangmnlove@163.com
|

签名由 网易邮箱大师 定制

On 01/24/2019 17:55, xingtaoshi wrote:

2019-01-24 17:51:34.649 ERROR com.alibaba.nacossync.extension.impl.ZookeeperSyncToNacosServiceImpl Line:149 - sync task from zookeeper to nacos was failed, taskId:3475b1b5c930dfe1f4f19001155c7e87
java.lang.NullPointerException: null
at com.alibaba.nacossync.extension.impl.ZookeeperSyncToNacosServiceImpl.sync(ZookeeperSyncToNacosServiceImpl.java:93)
at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:55)
at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:80)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:71)

**Comment by xingtaoshi** [comment]
确认 nacos 和zk 的配置都是正确的

**Comment by paderlol** [comment]
> 确认 nacos 和zk 的配置都是正确的

我这边试着重现你说的这个问题,发现只有在zk连接不上的时候才会出现这个问题。
