### ISSUE TITLE
Eureka sync to nacos (EurekaSyncToNacosServiceImpl line96 npe)

### ISSUE THREAD

**Issue by HRNonono** [nacos-group/nacos-sync#97]
eureka sync to nacos报错
EurekaSyncToNacosServiceImpl 96行 空指针错误，debug发现是
EurekaHttpClient eurekaHttpClient = eurekaServerHolder.get(taskDO.getSourceClusterId(), null); eurekaServerHolder的size为0

2019-07-07 20:44:08.638 INFO  com.alibaba.nacossync.extension.holder.AbstractServerHolder Line:39  - starting create cluster server,clusterId=f25df9683702cbc8fb629eb4eb74860a
2019-07-07 20:44:08.638 INFO  com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:92  - 从数据库中查询到一个删除任务，发出一个同步事件:TaskDO(id=4, taskId=858d2533dcd57996f762bc74d9a5a941, sourceClusterId=557fc9d1b1087776b2823c6b24fda8f5, destClusterId=f25df9683702cbc8fb629eb4eb74860a, serviceName=ORIGINSERVICE, version=, groupName=eureka, nameSpace=null, taskStatus=DELETE, workerIp=192.168.1.4, operationId=f12d9bcb-eec9-46cd-b121-3701ab3c89ae)
2019-07-07 20:44:11.647 INFO  com.alibaba.nacossync.extension.holder.AbstractServerHolder Line:39  - starting create cluster server,clusterId=557fc9d1b1087776b2823c6b24fda8f5
2019-07-07 20:44:11.648 ERROR com.alibaba.nacossync.extension.holder.AbstractServerHolder Line:46  - clusterId=557fc9d1b1087776b2823c6b24fda8f5,start server failed
java.lang.IllegalArgumentException: Malformed serviceUrl: 127.0.0.1:8761
	at com.netflix.discovery.shared.resolver.DefaultEndpoint.<init>(DefaultEndpoint.java:45)
	at com.alibaba.nacossync.extension.holder.EurekaServerHolder.createServer(EurekaServerHolder.java:36)
	at com.alibaba.nacossync.extension.holder.EurekaServerHolder.createServer(EurekaServerHolder.java:29)
	at com.alibaba.nacossync.extension.holder.AbstractServerHolder.lambda$get$1(AbstractServerHolder.java:42)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.alibaba.nacossync.extension.holder.AbstractServerHolder.get(AbstractServerHolder.java:40)
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:93)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:55)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-07 20:44:11.649 INFO  com.alibaba.nacossync.extension.holder.AbstractServerHolder Line:39  - starting create cluster server,clusterId=f25df9683702cbc8fb629eb4eb74860a
2019-07-07 20:44:11.649 ERROR com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl Line:117 - sync task from eureka to nacos was failed, taskId:858d2533dcd57996f762bc74d9a5a941
java.lang.NullPointerException: null
	at com.alibaba.nacossync.extension.impl.EurekaSyncToNacosServiceImpl.sync(EurekaSyncToNacosServiceImpl.java:96)
	at com.alibaba.nacossync.extension.SyncManagerService.sync(SyncManagerService.java:55)
	at com.alibaba.nacossync.event.listener.EventListener.listenerSyncTaskEvent(EventListener.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.lambda$run$0(QuerySyncTaskTimer.java:85)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.alibaba.nacossync.timer.QuerySyncTaskTimer$CheckRunningStatusThread.run(QuerySyncTaskTimer.java:76)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-07-07 20:44:11.649 INFO  com.alibaba.nacossync.timer.QuerySyncTaskTimer Line:86  - 从数据库中查询到一个同步任务，发出一个同步事件:TaskDO(id=4, taskId=858d2533dcd57996f762bc74d9a5a941, sourceClusterId=557fc9d1b1087776b2823c6b24fda8f5, destClusterId=f25df9683702cbc8fb629eb4eb74860a, serviceName=ORIGINSERVICE, version=, groupName=eureka, nameSpace=null, taskStatus=SYNC, workerIp=192.168.1.4, operationId=c9fdecea-948c-412e-a729-10f5b65dac31)

**Comment by glameyzhou** [comment]
先通过eureka open api看下对应的服务列表是否都存在，形如：
http://ip:port/eureka/apps/${serviceName}

你那边异常 eureka Holder为空，说明创建实例失败了，注意下eureka对应的connect_key_list值应该是http://ip:port/eureka，不能直接写一个IP。

**Comment by zhengzepeng** [comment]
看DefaultEndpoint构造函数：
`
public DefaultEndpoint(String serviceUrl) {
        this.serviceUrl = serviceUrl;

        try {
            URL url = new URL(serviceUrl);
            this.networkAddress = url.getHost();
            this.port = url.getPort();
            this.isSecure = "https".equals(url.getProtocol());
            this.relativeUri = url.getPath();
        } catch (Exception var3) {
            throw new IllegalArgumentException("Malformed serviceUrl: " + serviceUrl);
        }
    }

`
其拿到url去建立连接，表明送进去的是一个完整的地址，如http://127.0.0.1:1234/eureka

**Comment by liangxp** [comment]
兄弟是不是集群的IP列表配置错误了，eureka的IP列表应该配置成“http://IP:port/eureka”这种形式
